Feat custom tags
ShragaUser/BlueBoard pull request #76
Opened 2019-07-29 13:27 UTC by samuel404

added custom tags to boards and cards

2019-07-29 19:52 UTC, ShragaUser commented
commits are bad - not explanatory at all!

2019-07-29 20:05 UTC, ShragaUser requested changes
remove all comments 
remove all console.log() 
always use deconstruct
refactor functions -> too long and too much responsibility.

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/Board/Board.jsx
> +    console.log(this.props.boardLabels);
delete console.log()

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/Board/Board.jsx
> +      if(this.props.cards[cardId].labels && oldLabels.includes(this.props.cards[cardId].labels[0])){
this.props.cards should be const { cards } = this.props;

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/Board/Board.jsx
> +      cardsId = cardsId.concat(list.cards);
no need. 
just go over each card in list.  and do whatever is needed.

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/Board/Board.jsx
> +    cardsId.forEach(cardId => {
take out to different function.

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/Board/Board.jsx
> +              this.props.boardLabels.forEach(label => {
deconstruct boardLabels

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/Board/Board.jsx
> +  }
this whole function should be refactored. 
can be a lot more efficient!

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/BoardHeader/ColorPicker.jsx
> +
delete space

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/BoardList/BoardList.jsx
> +  return{
no need for return. 
can be implicit

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/CardBadges/CardBadges.jsx
> +  shouldComponentUpdate(nextProps){
delete if not necessary

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/CardBadges/CardBadges.jsx
> +    this.props.boardLabels.map(label => {
deconstruct

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/CardBadges/CardBadges.jsx
> +  const boardLabel = state.boardsById[ownProps.boardId].labels;
just rename to boardLabels and then return { boardLabels }

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/CardModal/CardOptions.jsx
> +    this.toggelEdit = this.toggelEdit.bind(this);
why though?

2019-07-29 20:05 UTC, ShragaUser commented on src/app/components/CardModal/CardOptions.jsx
> +  editModeCheack = label => {
check

2019-08-01 12:08 UTC, ShragaUser requested changes
simple change

2019-08-01 12:08 UTC, ShragaUser commented on src/app/components/Board/Board.jsx
> +          boardLabels.forEach(label => {
create single map object with key being: "inprogress" and value veing id. 
then just use labelIdMap[label]...

2019-08-07 06:51 UTC, dorweitman approved these changes
Shit work

2019-08-07 06:54 UTC, ShragaUser approved these changes
Yas

2019-08-07 06:54 UTC, merged